// Automatically generated by astro-icon
// c6aa8359bb607018049fb8dadf653725cda83df5ddb2b7d136005bddbe33f805

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "github"
		| "linkedin"
		| "x";
}