// Automatically generated by astro-icon
// 11dd06fe4bac7d1100a335b39cd80fb00e5295493a6e53617bdd4103812c891b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "github"
		| "linkedIn"
		| "x";
}